### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by versipellis** [davidanthoff/NodeJS.jl#17]
I'm trying to build NodeJS as part of DataVoyager, and I get thrown a fatal error. The error log provides no details. Any ideas?

┌ Error: Error building NodeJS:
│ fatal: error thrown and no exception handler available.

**Comment by davidanthoff** [comment]
Hm, tricky to debug based off that. What versions of julia, OS etc are you running on?

**Comment by versipellis** [comment]
Pretty much my thoughts, hahah.

Ubuntu 18.10, Julia 1.0.2. Anaconda install using a separate datascience environment. Tried it on the REPL and in Jupyter.

**Comment by davidanthoff** [comment]
And ``deps/build.log`` is empty?

**Comment by versipellis** [comment]
This is.. Strange. Reinstalling Julia seems to have fixed it. Welp.

`deps/build.log` had the exact same thing my terminal printed, which wasn't anything particularly helpful. I don't have it anymore, though :|

**Comment by davidanthoff** [comment]
Alright, please do let me know if it shows up again!
