### ISSUE TITLE
Test on FreeBSD

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/NodeJS.jl#31]
@ararslan, I just moved everything over to the artifact stuff on Julia 1.3. There are no pre-built binaries of node for FreeBSD, so I can't ship them with the artifact system. BUT, the package should now work such that if we don't have our own pre-built binaries, then it should just try to use a system `node`, just hoping that something is installed.

Could you try that on your FreeBSD system? Essentially, try to install node via the FreeBSD package manager, then add `master` of this package and try to run the tests. And hope that tests pass :)

**Comment by ararslan** [comment]
Looks like NodeJSBuilder uses Node 12, which is available in the FreeBSD Ports Collection but is not yet available to install via `pkg`, the FreeBSD binary package manager. Once it shows up there I'll try it out. (I hate installing ports...)

It appears that NodeJSBuilder repackages the existing Node distributions for other platforms. If you were to ever make it a "true" builder, it seems the patches required for it to work on FreeBSD are surprisingly minimal. [Here](https://svnweb.freebsd.org/ports/head/www/node12/files/) is the patch list, and most of these are for architectures we don't support for Julia on FreeBSD.

**Comment by davidanthoff** [comment]
Yes, NodeJSBuilder uses node 12, but this package here should fall back to whatever version of node happens to be installed on your system, so I think it would be worth trying this package here with whatever version of node you get via `pkg` on FreeBSD.

Yes, a true builder would be great. BUT, beyond my skills :)

One worry I would have is whether binaries that are built for node would work with our own cross compiled version of node (because then we might end up in a situation where our node was compiled with whatever version of gcc we use, but the binaries for some node package might be compiled with whatever compiler the standard node distribution uses).

One really nice thing about our own build though would be that we could potentially run the node engine within the julia process, and then run javascript in the julia process. I think there is a hosting interface for node that should enable that...

**Comment by ararslan** [comment]
> so I think it would be worth trying this package here with whatever version of node you get via pkg on FreeBSD.

Actually it seems I misread the Node availability in `pkg`; installing `node` gets you 12.10.0. With that, the NodeJS.jl tests "pass," but only because it skips the actual `@test` calls. (Which would fail due to version mismatches, since you test for 12.13.something.)

> One worry I would have is whether binaries that are built for node would work with our own cross compiled version of node

There's only one way to find out! 😄 But actually I bet it would be just fine. Aren't most Node packages written in JavaScript anyway rather than C?

**Comment by davidanthoff** [comment]
Ok, perfect! Yes, it skips the actual tests, but if there is no error then it means it was able to start node and npm, and that is good enough :)

Most node packages yes, but the one I care about is node-canvas (for vega-lite), and that has binary deps :)
