### ISSUE TITLE
Support Deno?

### ISSUE THREAD

**Issue by PallHaraldsson** [davidanthoff/NodeJS.jl#50]
FYI: https://stackoverflow.blog/2020/05/22/deno-v1-0-0-released-to-solve-node-js-design-flaws/

>Node.js creator, Ryan Dahl, [left in 2012, and since] decided to create a new implementation of his original idea: Deno, which released V1.0.0 last week. [..]
>It’s built in Rust to be fast and includes a plugin API. Deno is designed to be a series of Rust crates, with deno_core as the primary, barebones runtime. Another crate provides bindings to the JavaScript V8 C++ API. So if another version of JavaScript supplants V8, all Deno needs to do is provide a new crate. 
>
>For many, the killer feature included in Deno will be the native support for TypeScript.
> [..]
>But no piece of web tech is an island these days, and Deno—like Node.js—will support a vast ecosystem of modules and dependencies. Node.js did this with npm, but though it had a central repository with npm, it was unable to prevent bad actors.

I'm not pushing for support, just letting you know. I'm not sure if there's much demand for NodeJS.jl, but it seems you still maintain it unlike this dead project:

https://www.npmjs.com/package/node-julia

**Comment by davidanthoff** [comment]
I think a Deno.jl package would be awesome! But I don't think it belongs in here.

NodeJS.jl as it stands right now is a key part of VegaLite.jl, so it is pretty heavily used.

**Comment by fonsp** [comment]
We are working on it! https://github.com/Pangoraw/Deno.jl
